Feature/add login screen
Uyoshima/RSSReader-Maruyama pull request #2
Opened 2020-09-05 11:18 UTC by Uyoshima

ログイン画面の作成。

CocoaPods経由で以下を導入しています。
- RealmSwift
- SwiftyXMLParser
- Alamofire
- Swifter
- FBSDKCoreKit
- FBSDKLoginKit
- FBSDKShareKit
- GoogleSignIn
- cocoapods-keys

ItemListTabBarController.swiftでUserDefaultsにUserデータがない場合、LoginViewControllerを表示しています。
Apple SignIn Buttonは現在Apple Developer Programに加入していないため、未実装です。

よろしくお願いします。

2020-09-05 11:35 UTC, Karibash commented
プロジェクトルートへ.gitignoreを作成しコミットしてください。
不要なファイルがコミット対象から外れるようになります。
[参考ファイル](https://github.com/Karibash/RxCoreNFC/blob/master/.gitignore)

2020-09-05 11:36 UTC, Karibash commented
> CocoaPods経由で以下を導入しています。

Podfileが無いと他の人がビルドできないのでコミットするようにお願いします。

2020-09-05 11:42 UTC, Karibash commented
@Uyoshima 
DataModelフォルダをModelsに名称変更お願いします。
Model自体にデータの構造体という意が含まれているので接頭辞にDataを付けるのは冗長です。

2020-09-05 13:27 UTC, Karibash requested changes

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
クラス名に安易にManager等と名付けるのは避けたほうがいいです。
Managerでは意味合いが広すぎて後々クラスが肥大化してしまい保守が難しくなる可能性が高いです。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let userData = self.userDefault.object(forKey: UD_USER_DATA_KEY) as! Data
```suggestion
        guard let userData = userDefaults.data(forKey: USER_DATA_KEY) else {
            return nil
        }
```
selfは基本的に付けなくて大丈夫です。
userDataが取得できるとは限らないので、guard文を使用してnilだった場合は即時returnするようにしましょう。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    private let UD_USER_DATA_KEY = "userdata"
```suggestion
    private let UD_USER_DATA_KEY = "userData"
```
lowerCamelにしましょう

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    private let UD_USER_DATA_KEY = "userdata"
```suggestion
    private let USER_DATA_KEY = "userData"
```
接頭辞UD_はどういった意味で付けているのでしょうか？
UserDataの略称でしょうか？必要ないように思えますが

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    lazy var userDefault = UserDefaults.standard
```suggestion
    lazy var userDefaults = UserDefaults.standard
```
UserDefaults.standardの返り値はUserDefaultsクラスのインスタンスなので変数名もuserDefaultsにするのが適切です。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func saveUserData(user: User) {
```suggestion
    func save(user: User) {
```
UserDataManagerにsaveUserDataは冗長な気がします。
saveだけでも意味は通じるのではないでしょうか？

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func removeUserData() {
```suggestion
    func delete() {
```
保存がsaveならば削除はdeleteの方が自然では無いでしょうか？

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        self.userDefault.removeObject(forKey: UD_USER_DATA_KEY)
```suggestion
        userDefaults.removeObject(forKey: USER_DATA_KEY)
```
ここもself.は不要です。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let UserData = try? JSONEncoder().encode(user)
```suggestion
        let userData = try? JSONEncoder().encode(user)
```
変数はlowerCamelで定義しましょう。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        self.userDefault.set(UserData, forKey: UD_USER_DATA_KEY)
```suggestion
        userDefaults.set(userData, forKey: USER_DATA_KEY)
```

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let user = userDefault.object(forKey: UD_USER_DATA_KEY ) as? Data
```suggestion
        let user = userDefaults.data(forKey: USER_DATA_KEY)
```
dataにキャストする処理は不要です。
UserDefaultsにData型でデータを取得できるメソッドが用意されているのでそちらを使用してください。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func getUserData() -> User {
```suggestion
    func load() -> User? {
```
保存がsaveなら読み取りはloadの方が適切では無いでしょうか。
また、ユーザーデータが端末に保存されているとは限られないので、返り値はOptionalにしておきましょう。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let user = try! JSONDecoder().decode(User.self, from: userData)
try!だとユーザーデータが保存されていない場合エラーでアプリが落ちませんか？

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        if user != nil {
```suggestion
        return user != nil
```
if文を使用しなくてもreturnできます。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func isLoggedIn() -> Bool {
```suggestion
    func exists() -> Bool {
```
isLoggedInで行っている処理を見直してください。
ログイン状態の確認ではなく、userDetaulsへデータが保存されているかどうかの確認ですよね。
関数名も実装内容に則った名前にしましょう。

2020-09-05 13:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
UserDataManagerに今後どういった処理を追加していくつもりなのか箇条書きで良いので返答お願いします。

2020-09-05 13:30 UTC, Karibash requested changes

2020-09-05 13:30 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
```suggestion
class UserDataManager {
```
NSObjectの継承は不要です。

2020-09-05 14:17 UTC, Karibash requested changes

2020-09-05 14:17 UTC, Karibash commented on RSSReader-Maruyama/DataModel/User.swift
> +class User: NSObject, Codable {
```suggestion
class User: Codable {
```
NSObjectの継承は不要です。

2020-09-05 14:17 UTC, Karibash commented on RSSReader-Maruyama/DataModel/User.swift
> +class User: NSObject, Codable {
```suggestion
struct User: Codable {
```
データの構造を表すクラスを定義する際はstructを使用しましょう。

2020-09-05 14:17 UTC, Karibash commented on RSSReader-Maruyama/DataModel/User.swift
> +    let userID: String!
```suggestion
    let id: String
```
idのみでも意味が通じるのでidに変更しましょう。
また！は不要です。

2020-09-05 14:17 UTC, Karibash commented on RSSReader-Maruyama/DataModel/User.swift
> +    init(userID: String!) {
structを使用すると暗黙的にイニシャライザが定義されるので、ここの初期化処理は不要です。

2020-09-05 16:08 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    private let UD_USER_DATA_KEY = "userdata"
lowerCamelで、かしこまりました。
UDは「UserDefaults」の略で付けました。削除したほうがよろしいでしょうか？

2020-09-05 16:22 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
`UserDataManagerに今後どういった処理を追加していくつもりなのか箇条書きで良いので返答お願いします。`
・Userオブジェクトの設定情報の更新(フォントサイズ等)
です。

2020-09-05 17:02 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let userData = self.userDefault.object(forKey: UD_USER_DATA_KEY) as! Data
修正しました。

2020-09-05 17:02 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    lazy var userDefault = UserDefaults.standard
修正しました。

2020-09-05 17:02 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func saveUserData(user: User) {
修正しました。

2020-09-05 17:03 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func removeUserData() {
確かにその様に思います。
修正しました。

2020-09-05 17:03 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        self.userDefault.removeObject(forKey: UD_USER_DATA_KEY)
修正しました。

2020-09-05 17:03 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let UserData = try? JSONEncoder().encode(user)
修正しました。

2020-09-05 17:03 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        self.userDefault.set(UserData, forKey: UD_USER_DATA_KEY)
修正しました。

2020-09-05 17:04 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        let user = userDefault.object(forKey: UD_USER_DATA_KEY ) as? Data
修正しました。

2020-09-05 17:04 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func getUserData() -> User {
修正しました。

2020-09-05 17:05 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +        if user != nil {
修正しました。

2020-09-05 17:06 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    func isLoggedIn() -> Bool {
かしこまりました。

2020-09-05 17:23 UTC, Uyoshima commented on RSSReader-Maruyama/DataModel/User.swift
> +    let userID: String!
修正しました。

2020-09-05 17:24 UTC, Uyoshima commented on RSSReader-Maruyama/DataModel/User.swift
> +    init(userID: String!) {
修正しました。

2020-09-06 03:18 UTC, Karibash commented
現状のままではこのプロジェクトが依存しているRubyのパッケージ、バージョンが不明瞭な為、下記の記事を参考にGemfileを追加お願いします。
https://mataku.com/2017/03/13/how-to-load-env-val-in-ios/

2020-09-06 08:27 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
つまりUserDataManagerは下記の役割を担っているという認識でよろしいでしょうか？
・UserDefaultsからユーザデータの取得
・UserDefaultsへのユーザデータの保存
・UserDefaultsからユーザデータの削除
・一覧画面の表示変更
・RSS取得間隔変更
・購読RSS管理
・文字サイズ変更

2020-09-06 09:29 UTC, Karibash requested changes

2020-09-06 09:29 UTC, Karibash commented on RSSReader-Maruyama/DataManagers/UserDataManager.swift
> +
```suggestion
```
改行が１つ多いです。

2020-09-06 09:29 UTC, Karibash commented on RSSReader-Maruyama/DataManagers/UserDataManager.swift
> +        let user = try? JSONDecoder().decode(User.self, from: userData)
```suggestion
        return try? JSONDecoder().decode(User.self, from: userData)
```
ここで変数に一度格納する必要性は無いと思います。そのままreturnしましょう。

2020-09-06 09:40 UTC, Karibash requested changes

2020-09-06 09:40 UTC, Karibash commented on RSSReader-Maruyama/AppDelegate.swift
```suggestion
```
改行が多いです。
基本的に改行はを入れる場合は１つにしてください。

2020-09-06 09:40 UTC, Karibash commented on RSSReader-Maruyama/AppDelegate.swift
> +                                                annotation: options[UIApplication.OpenURLOptionsKey.annotation] )
```suggestion
        ApplicationDelegate.shared.application(app,
                                               open: url,
                                               sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String,
                                               annotation: options[UIApplication.OpenURLOptionsKey.annotation])
```
メソッド呼び出し時に改行を入れる場合は引数毎に改行するようにしてください。

2020-09-06 09:40 UTC, Karibash commented on RSSReader-Maruyama/SceneDelegate.swift
> +        ApplicationDelegate.shared.application( UIApplication.shared, open: url, sourceApplication: nil, annotation: [UIApplication.OpenURLOptionsKey.annotation] )
```suggestion
        ApplicationDelegate.shared.application(UIApplication.shared,
                                               open: url,
                                               sourceApplication: nil,
                                               annotation: [UIApplication.OpenURLOptionsKey.annotation])
```
[AppDelegate](https://github.com/Uyoshima/RSSReader-Maruyama/pull/2/files#diff-424d8be69036384732c145debf8741e9R33)で呼び出している時と同じように改行しましょう。

2020-09-06 09:46 UTC, Karibash requested changes

2020-09-06 09:46 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginButton.swift
> +     super.init(frame: frame)
```suggestion
        super.init(frame: frame)
```
インデントずれてます。

2020-09-06 09:46 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginButton.swift
> +     super.init(coder: aDecoder)
```suggestion
        super.init(coder: aDecoder)
```
インデントずれてます。

2020-09-06 09:46 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginButton.swift
> +     super.prepareForInterfaceBuilder()
```suggestion
        super.prepareForInterfaceBuilder()
```
インデントずれてます。

2020-09-06 09:46 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginButton.swift
> +     iconView.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 20).isActive = true
```suggestion
        clearsContextBeforeDrawing = true
        translatesAutoresizingMaskIntoConstraints = false
        heightAnchor.constraint(equalToConstant: 45).isActive = true
        layer.masksToBounds = true
        layer.cornerRadius = 8
        layer.borderWidth = 1.5
        layer.borderColor = UIColor.black.cgColor
        backgroundColor = .white
        setTitleColor(.black, for: .normal)
        titleLabel?.font = UIFont.systemFont(ofSize: 16, weight: .medium)
        setTitle(text, for: .normal)
        
        let iconView = UIImageView()
        addSubview(iconView)
        iconView.contentMode = .scaleAspectFit
        iconView.centerYAnchor.constraint(equalTo: self.centerYAnchor).isActive = true
        iconView.translatesAutoresizingMaskIntoConstraints = false
        iconView.image = UIImage(named: icon)
        iconView.widthAnchor.constraint(equalToConstant: 25).isActive = true
        iconView.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 20).isActive = true
```
インデントずれてます。

2020-09-06 10:36 UTC, Karibash requested changes

2020-09-06 10:36 UTC, Karibash commented on RSSReader-Maruyama/AppDelegate.swift
> +                                               annotation: options[UIApplication.OpenURLOptionsKey.annotation] )
```suggestion
                                               annotation: options[UIApplication.OpenURLOptionsKey.annotation])
```
不要なスペースが入ってます。

2020-09-06 10:36 UTC, Karibash commented on RSSReader-Maruyama/SceneDelegate.swift
> +                                               annotation: [UIApplication.OpenURLOptionsKey.annotation] )
```suggestion
                                               annotation: [UIApplication.OpenURLOptionsKey.annotation])
```
不要なスペースが入ってます。

2020-09-06 12:45 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    private let UD_USER_DATA_KEY = "userdata"
UserDefaultsのKeyで有ることを明示したいのであれば下記のようにExtensionを実装することをオススメします。
```swift
extension UserDefaults {
    enum Keys : String{
        case userData
    }
}

// example
let userData = UserDefaults.standard.data(forKey: UserDefaults.Keys.userData.rawValue)
```

2020-09-06 12:48 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
あっております。
しかし、こうやって見てみると
・一覧画面の表示変更
・RSS取得間隔変更
・購読RSS管理
・文字サイズ変更
に関してはFeedsSettingsクラスなどを作成して管理するべきと思いました。
どうでしょうか？

2020-09-06 12:53 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +    private let UD_USER_DATA_KEY = "userdata"
確かにこちらの方が、より理解りやすく便利ですね。
ありがとうございます。

2020-09-06 13:39 UTC, Karibash requested changes

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//MARK:- Setup SignIn Button
```suggestion
    // MARK: - Setup SignIn Button

```
インデントがずれています。
またMarkコメントのあとは改行を入れましょう。

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//    MARK: Facebook SignIn Action
```suggestion
    // MARK: - Facebook SignIn Action

```
Markコメントの書き方は統一してください

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//    MARK: Apple ID SignIn Action
```suggestion
    // MARK: - Apple ID SignIn Action
```

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//    MARK: Apple ID SignIn Action
```suggestion
    // MARK: - Apple ID SignIn Action

```

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//MARK:- Delegate
```suggestion

// MARK: - Delegate

```

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//MARK: Apple SignIn
```suggestion
// MARK: - Apple SignIn
```

2020-09-06 13:39 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +//MARK: Google SignIn
```suggestion
// MARK: - Google SignIn
```

2020-09-06 15:23 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
> しかし、こうやって見てみると
> ・一覧画面の表示変更
> ・RSS取得間隔変更
> ・購読RSS管理
> ・文字サイズ変更
> に関してはFeedsSettingsクラスなどを作成して管理するべきと思いました。

それはそうですね。作るべきです。
１つのクラスが持つ責任は１つだけであるべきです。
今回の場合UserDataManagerの責務は端末へユーザーのデータを保存/更新する事です。
そこへさらに設定の変更処理も追加してしまうと、単一責任原則へ違反したコードになってしまいます。
[単一責任(SOLID)原則](https://thinkit.co.jp/article/13274)について勉強しておいてください。

> クラス名に安易にManager等と名付けるのは避けたほうがいいです。
> Managerでは意味合いが広すぎて後々クラスが肥大化してしまい保守が難しくなる可能性が高いです。

最初の頃に上記のような指摘をしましたが、何らかのデータを保存/更新/取得するクラスはよくHogeHogeRepositoryと名付けられる事が多いです。
なのでUserDataManagerもUserクラスを保存/更新/取得クラスという意味を込めてUserRepositoryへ変更しましょう。
フォルダ名の変更も忘れないように、DataManagersではなくRepositoriesへ

2020-09-07 13:27 UTC, Karibash requested changes

2020-09-07 13:27 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginButton.swift
> +class LoginButton: UIButton {
カスタムUIViewをあまり使いこなせていないです。
StoryboardでButtonを設置し、CustomClassを設定し扱うようにしましょう。
<img width="1680" alt="スクリーンショット 2020-09-07 22 14 55" src="https://user-images.githubusercontent.com/40270352/92391784-36618c00-f158-11ea-837d-b88e5200d8c7.png">

IBInspectableを使用すると下記のようにStoryboard側で設定値を変更できるようになります。
<img width="1676" alt="スクリーンショット 2020-09-07 22 24 41" src="https://user-images.githubusercontent.com/40270352/92392328-0ebef380-f159-11ea-94dd-03382d22d911.png">

下記にサンプルコードを提示しておきます。

```swift
import Foundation
import UIKit

@IBDesignable
class IconableButton: UIButton {
    lazy var iconImageView: UIImageView = {
        let imageView = UIImageView()
        addSubview(imageView)
        imageView.contentMode = .scaleAspectFit

        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.widthAnchor.constraint(equalToConstant: 25).isActive = true
        imageView.centerYAnchor.constraint(equalTo: centerYAnchor).isActive = true
        imageView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 20).isActive = true
        return imageView
    }()
    
    @IBInspectable var iconImage: UIImage? = nil {
        didSet {
            iconImageView.image = iconImage
        }
    }

    @IBInspectable var cornerRadius: CGFloat = 8 {
        didSet {
            layer.cornerRadius = cornerRadius
        }
    }

    @IBInspectable var borderWidth: CGFloat = 1.5 {
        didSet {
            layer.borderWidth = borderWidth
        }
    }
    
    @IBInspectable var borderColor: UIColor = UIColor.black {
        didSet {
            layer.borderColor = borderColor.cgColor
        }
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    override func prepareForInterfaceBuilder() {
        super.prepareForInterfaceBuilder()
        setup()
    }
  
    private func setup() {
        layer.cornerRadius = cornerRadius
        layer.borderWidth = borderWidth
        layer.borderColor = borderColor.cgColor
    }

}
```

2020-09-07 13:28 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
ありがとうございます。
具体例も出して頂き、とてもわかり易かったです。
クラス名、修正致しました。

2020-09-07 14:12 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginButton.swift
> +class LoginButton: UIButton {
ありがとうございます。
今後はできるだけInterface builderを使用するように心掛けます。

2020-09-08 14:17 UTC, Karibash commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
DataRepositorysのDataは不要です。
あとRepositoyの複数形はRepositoriesです。

2020-09-08 15:42 UTC, Karibash requested changes

2020-09-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private func setupAppleSignInButtons() {
IconableButtonでも使用している用にLazyInitializationを使用する事によりUIの宣言処理を分離する事ができます。

```swift
private lazy var appleLoginButton: ASAuthorizationAppleIDButton = {
    let appleLoginButton = ASAuthorizationAppleIDButton()
    appleLoginButton.addTarget(self, action: #selector(didPushLoginButtonApple), for: .touchUpInside)     
    appleLoginButton.heightAnchor.constraint(equalToConstant: 45).isActive = true
    return appleLoginButton
}()
```

また注意点としてLazyInitializationは変数を参照するまで生成されない為、viewDidLoadでaddArrangedSubviewするようにしましょう。

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    loginButtonStackView.addArrangedSubview(appleLoginButton)
}
```

2020-09-09 11:14 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private func setupAppleSignInButtons() {
ありがとうございます。
勉強になります。

2020-09-10 14:25 UTC, Karibash requested changes

2020-09-10 14:25 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    @IBAction func didPushLoginButtonFacebook() {
extensionを使って処理を分類化するとコードが見やすくなるのでおすすめです。

```swift
// MARK: - Facebook Login Action

private extension LoginViewController {
    @IBAction func didPushFacebookLoginButton() {
        let loginManager = LoginManager()
        let permission: [Permission] = [.publicProfile, .email]
        loginManager.logIn(permissions: permission, viewController: self) { (result) in
            switch result {
            case .success:  self.didSuccessFacebookLogin()
            case .failed(_): break
            default: break
            }
        }
    }
    
    func didSuccessFacebookLogin() {
        if let accessToken = AccessToken.current {
            print("\(accessToken.userID)")
            loginSuccessAction(userID: accessToken.userID)
        }
    }
}
```

2020-09-11 11:27 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    @IBAction func didPushLoginButtonFacebook() {
こういう使い方もあるんですね。
ありがとうございます。

LoginViewControllerでしたので、Loginに統一しました。

2020-09-11 15:29 UTC, Karibash requested changes

2020-09-11 15:29 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
下記のようにDelegateも継承させてあげるとより良いかと思います。
また、処理を見ればすぐに分かるような箇所にはコメントは不要です。
良いコードというのはコメントが無くても処理が理解出来るものです。
コメントは仕様に伴った複雑な処理のみ記載するようにしましょう。

```suggestion
extension LoginViewController: GIDSignInDelegate  {
    @IBAction func didPushLoginButtonGoogle() {
        GIDSignIn.sharedInstance()?.delegate = self
        GIDSignIn.sharedInstance()?.signIn()
    }
    
    func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {
        if error == nil {
            loginSuccessAction(userID: user.userID)
        } else {
            print("error: \(error!.localizedDescription)")
        }
    }
}
```

2020-09-11 15:29 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
これらのDelegateもdidPushLoginButtonAppleメソッドを実装しているextensionに継承させると良いでしょう。

2020-09-12 14:28 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
ありがとうございます。
GIDSignInDelegateで無いものを実装してしまうのは良くないと思っていました。
修正しました。

2020-09-12 14:28 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
修正しました。

2020-09-12 14:31 UTC, Uyoshima commented on RSSReader-Maruyama/DataManager/UserDataManager.swift
> +class UserDataManager: NSObject {
修正しました。

2020-09-12 16:44 UTC, Karibash requested changes

2020-09-12 16:44 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        // self.performSegue(withIdentifier: SELECT_FEEDS_SEGUE_IDENTIFIER, sender: nil)
```suggestion
```
開発時の動作テストに用いていたコードはコミットしないようにしましょう。

2020-09-12 16:44 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +extension LoginViewController: ASAuthorizationControllerPresentationContextProviding {
```suggestion
extension LoginViewController: ASAuthorizationControllerDelegate {
    
}

extension LoginViewController: ASAuthorizationControllerDelegatem, ASAuthorizationControllerPresentationContextProviding {
```
１つに纏めてしまっても良いような気がします。

2020-09-12 16:44 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +// MARK: - Delegate
```suggestion
// MARK: - Extensions
```
DelegateからExtensionsへ変更し、// MARK: - Facebook Login Actionの上部に改行を１つ入れて記述しましょう。

2020-09-12 16:48 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
GoogleSignInの実装方法がGoogleのドキュメントと違うような気がするのですが、どのサイトを見て実装されたのでしょうか？
https://developers.google.com/identity/sign-in/ios#swift

2020-09-12 17:09 UTC, Karibash requested changes

2020-09-12 17:09 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +             print("\(accessToken.userID)")
```suggestion
```
開発時に使用していたログ出力はコミット前に削除するようにしましょう。
動作確認としてログを残しておきたいのであれば、もう少し詳細なログを出力するようにしましょう。
```swift
print(“\(String(describing: self)).\(#function) #\(#line): FaceBookログイン完了 ユーザーID[\(accessToken.userID)]“)
```
また上記のようなコードを毎回書くのも面倒なので、本格的にログ出力したい場合は下記の記事のようにLoggerを作成した方が良いです。
https://qiita.com/shtnkgm/items/cf68a736f81b958c71f9

2020-09-13 06:08 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        // self.performSegue(withIdentifier: SELECT_FEEDS_SEGUE_IDENTIFIER, sender: nil)
画面遷移先を実装しない(LoginViewController作成のみの)場合、どの様に記載すればよいのでしょうか？

2020-09-13 06:28 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +extension LoginViewController: ASAuthorizationControllerPresentationContextProviding {
修正しました。

2020-09-13 06:28 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +// MARK: - Delegate
修正しました。

2020-09-13 06:29 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
https://dev.classmethod.jp/articles/ios-google-signin/
こちらの記事を参考にしました。

2020-09-13 06:30 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +             print("\(accessToken.userID)")
開発時のログ出力は削除するように気をつけます。
Loggerに関する記事も紹介頂き、ありがとうございます。

2020-09-13 12:17 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        // self.performSegue(withIdentifier: SELECT_FEEDS_SEGUE_IDENTIFIER, sender: nil)
> 画面遷移先を実装しない(LoginViewController作成のみの)場合、どの様に記載すればよいのでしょうか？

未実装の部分をどうコメントすれば良いかという事でしょうか？
その場合は下記のようにToDoコメントを使用する事をお勧めします。
```swift
// ToDo: Feed選択画面へ遷移させる
```

2020-09-13 13:10 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
didPushLoginButtonGoogleだとボタンを押下するたびにdelegateのセット処理が流れてしまうので、viewDidLoadでセットするように変更しましょう。

2020-09-15 16:15 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +}
確かにご指摘の通りですね。
ありがとうございます。

2020-09-15 16:16 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        // self.performSegue(withIdentifier: SELECT_FEEDS_SEGUE_IDENTIFIER, sender: nil)
基本的なことにも関わらず、教えていただいてありがとうございます。
今後、その様に致します。

2020-09-17 04:56 UTC, Uyoshima commented
.gitignoreの追加が出来ていないのに気が付き、追加しました。
頂いた参考ファイルと、https://github.com/github/gitignore/blob/master/Swift.gitignoreを照らし合わせてました。
ご確認、よろしくおねがいします。

2020-09-17 14:50 UTC, Karibash commented
> .gitignoreの追加が出来ていないのに気が付き、追加しました。
> 頂いた参考ファイルと、https://github.com/github/gitignore/blob/master/Swift.gitignore を照らし合わせてました。
> ご確認、よろしくおねがいします。

念のため下記記事を参考にgitignoreの反映をお願いいたします。
https://qiita.com/fuwamaki/items/3ed021163e50beab7154

2020-09-17 15:08 UTC, Karibash requested changes

2020-09-17 15:08 UTC, Karibash commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
ファイル名を取得する処理はLoggerクラスの責務では無いですね。
Stringクラスのextensionにファイル名を取得するプロパティを追加しましょう。

また文字(ファイルパス)から最後尾のパスを取得する処理は下記ように記述する事もできます。
```swift
extension String {
    
    public var lastPathComponent: String {
        return (self as NSString).lastPathComponent
    }
    
    public var fileName: String {
        return self.lastPathComponent.components(separatedBy: ".").first ?? ""
    }
}
```

2020-09-17 15:26 UTC, Karibash requested changes

2020-09-17 15:26 UTC, Karibash commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
DateからStringを生成する処理もExtensionに定義するようにしましょう。
```swift
extension Date {
    
    public func formatted(format: String) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = format
        return formatter.string(from: self)
    }
}
```

Loggerクラスでは"yyyy/MM/dd HH:mm:ss"を定数で保持するようにし、上記のようなExtensionを使用してStringを生成するようにすれば、他のクラスでも処理を使いまわせるようになります。
```swift
public struct Logger {
    private static let DATE_FORMAT = "yyyy/MM/dd HH:mm:ss"
    // ~~ 中略 ~~

    private static func printToConsole(logLevel: LogLevel, file:String, function: String, line: Int, message: String) {
        #if DEBUG
        print("\(Date().formatted(DATE_FORMAT)) [\(logLevel.rawValue.uppercased())] \(className(from: file)).\(function) #\(line): \(message)")
        #endif
    }
}
```

2020-09-17 16:08 UTC, Uyoshima commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
・.gitignoreについて
>念のため下記記事を参考にgitignoreの反映をお願いいたします。
https://qiita.com/fuwamaki/items/3ed021163e50beab7154
参考記事、ありがとうございます。
少し不安になり教えていただきたいのですが、ファイル指定がわからないので、
`$ git rm -r --cached . //ファイル全体キャッシュ削除`
をしようと思うのですが、こちらで大丈夫でしょうか？

・Loggerクラスについて。
汎用性のあるものはextensionで追加すれば、良いってことですね。
この際、`String+Extension.swift`だとファイル名の意味が大きすぎる様に思い、`String+FileName.swift`として機能別？にファイルを作成してしまうと、今回の様なものだと問題ないが、ファイル数が多くなってしまわないか？等考えてしまいます。
この様な時は何を基準に判断すれば良いですか？

2020-09-18 00:29 UTC, Karibash commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
> 少し不安になり教えていただきたいのですが、ファイル指定がわからないので、
$ git rm -r --cached . //ファイル全体キャッシュ削除
をしようと思うのですが、こちらで大丈夫でしょうか？

編集中のファイルがある場合はstashを使って退避させると良いでしょう
https://qiita.com/keisuke0508/items/4ad7caf544b1ad631fd7

2020-09-18 00:35 UTC, Karibash commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
> ・Loggerクラスについて。
汎用性のあるものはextensionで追加すれば、良いってことですね。

汎用性というところもありますが、今回の重要なところはどのクラスで処理するべきなのかという点です。
Loggerクラスはログ出力に関するロジックのみを記述するべきで、ファイル名を取得するロジックは別のクラスが持つべきです。

> この際、String+Extension.swiftだとファイル名の意味が大きすぎる様に思い、String+FileName.swiftとして機能別？にファイルを作成してしまうと、今回の様なものだと問題ないが、ファイル数が多くなってしまわないか？等考えてしまいます。
この様な時は何を基準に判断すれば良いですか？

一旦String+Extensionにしておいて、改修を重ねるにつれて拡張関数が増えてきたなと感じるようになってから分割すれば良いかと思います。

2020-09-18 09:44 UTC, Uyoshima commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
・.gitignoreに関して。
こちらキチンと出来ていますでしょうか？確認よろしくおねがいします。

2020-09-18 09:47 UTC, Uyoshima commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
・Extensionファイルについて
ありがとうございます！
以前ご指摘頂いた内容と被ってしまいましたね。。。申し訳ございません。
気をつけていきます。

2020-09-18 09:47 UTC, Uyoshima commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
修正しました。

2020-09-18 13:25 UTC, Karibash commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
> ・.gitignoreに関して。
こちらキチンと出来ていますでしょうか？確認よろしくおねがいします。

問題ないかと🙆‍♂️

2020-09-18 13:30 UTC, Karibash requested changes

2020-09-18 13:30 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +// MARK: - Extensions
```suggestion
```
`// MARK: - Extensions`は一番上の部分だけで大丈夫です。

2020-09-18 13:30 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +// MARK: - Extensions
```suggestion
```

2020-09-18 13:42 UTC, Karibash requested changes

2020-09-18 13:42 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate func showAlert(title: String, message: String, actions:[UIAlertAction]) {
```suggestion
    private func showAlert(title: String, message: String, actions:[UIAlertAction]) {
```
privateにしましょう

2020-09-18 13:42 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate func loginSuccessAction(userID: String) {
```suggestion
    private func loginSuccessAction(userID: String) {
```
privateにしましょう

2020-09-18 13:42 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate let userRepository = UserRepository()
```suggestion
    private let userRepository = UserRepository()
```
privateにしましょう

2020-09-18 13:43 UTC, Karibash commented
インデントがずれているところが何箇所かあります。
Command+A[全選択]した後にCtrl+i[整形]で修正お願いします。

2020-09-18 13:47 UTC, Karibash requested changes

2020-09-18 13:47 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            Logger.debug("Facebookログイン完了 ユーザーID [\(accessToken.userID)]")
Facebookログインでのみログを出力しているのに違和感を感じます。
出すなら他の箇所でもログを出力するようにしましょう。

2020-09-18 13:51 UTC, Karibash requested changes

2020-09-18 13:51 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +extension LoginViewController: ASAuthorizationControllerPresentationContextProviding, ASAuthorizationControllerDelegate {
Appleログインエラーの処理も記載しましょう。
`ASAuthorizationControllerDelegate `の`func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error)`を使用すれば実装可能かと思います。

2020-09-18 14:20 UTC, Uyoshima commented on RSSReader-Maruyama/Utilities/Logger.swift
> +    }
ご確認ありがとうございます！

2020-09-18 14:20 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +// MARK: - Extensions
かしこまりました。

2020-09-18 14:51 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +// MARK: - Extensions
削除しました。

2020-09-18 14:51 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate func loginSuccessAction(userID: String) {
変更しました。

2020-09-18 14:52 UTC, Karibash requested changes

2020-09-18 14:52 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate func showAlert(title: String, message: String, actions:[UIAlertAction]) {
アラートの表示処理もUIViewControllerのExtensionとして実装しておけば他の画面でアラートを表示する際にも処理を使いまわせるようになります。
また、配列を回す際はforEachを利用すると簡潔に記述できるようになります。
```swift
extension UIViewController {
   func showAlert(title: String, message: String, actions:[UIAlertAction]) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        actions.forEach { alert.addAction($0) }
        present(alert, animated: true, completion: nil)
    }
}
```

2020-09-18 15:10 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate let userRepository = UserRepository()
変更しました。

2020-09-18 15:11 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            Logger.debug("Facebookログイン完了 ユーザーID [\(accessToken.userID)]")
Google、Appleログインにも出力するようにしました。

2020-09-18 15:12 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +extension LoginViewController: ASAuthorizationControllerPresentationContextProviding, ASAuthorizationControllerDelegate {
実装しました。
また、成功時も記載いたしました。

2020-09-18 15:12 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    fileprivate func showAlert(title: String, message: String, actions:[UIAlertAction]) {
Extensionとしてファイルを作成しました。

2020-09-18 15:46 UTC, Karibash requested changes

2020-09-18 15:46 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private func loginSuccessAction(userID: String) {
```suggestion
    private func didLoginSuccess(userID: String) {
```
〜が完了した、〜された系のメソッドはdid~~に統一するようにしましょう。

2020-09-18 15:46 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            showAlert(title: "ログインエラー", message: "error: \(error!.localizedDescription)", actions: [closeAction])
ログイン失敗時の処理もログイン成功時と同じようにメソッドを切り出しましょう。
```swift
func didLoginFailed(_ error: Error) {
    let closeAction = UIAlertAction(title: "閉じる", style: .default, handler: nil)
    showAlert(title: "ログインエラー", message: "error: \(error!.localizedDescription)", actions: [closeAction])
}
```

2020-09-18 15:53 UTC, Karibash requested changes

2020-09-18 15:53 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            userID = "ユーザーID不明"
想定外の物が来た場合はログイン失敗扱いにするほうが良いのではないでしょうか。

2020-09-18 15:54 UTC, Karibash commented
ログイン失敗時のログも出力するようにしましょうか

2020-09-18 17:19 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            showAlert(title: "ログインエラー", message: "error: \(error!.localizedDescription)", actions: [closeAction])
ご指摘ありがとうございます。
ログイン成功したが、ユーザーIDが取得出来なかった際
```
   case let passwordCredential as ASPasswordCredential:
            userID = passwordCredential.user
        default:
            userID = "ユーザーID不明"
```
Error型のものが無いので、`didLoginFailed(errorMasaage: String)`のようにしても問題ないでしょうか？

2020-09-18 17:20 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            userID = "ユーザーID不明"
修正します。

2020-09-25 16:04 UTC, Uyoshima commented
お疲れさまです。
こちらいかがでしょうか？
確認いただけると幸いです。

2020-09-27 11:25 UTC, Karibash commented
> お疲れさまです。
> こちらいかがでしょうか？
> 確認いただけると幸いです。

すみません。ちょっと最近プライベートが忙しくあまり見れてなかったです...

2020-09-27 12:18 UTC, Karibash requested changes

2020-09-27 12:18 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private func didLoginSuccessAction(userID: String) {
```suggestion
    private func didLoginSucceeded(userID: String) {
```

ログイン失敗時の関数名と記法を揃えましょう。

2020-09-27 12:18 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        else {
```suggestion
        } else {
```
else節は改行せずに書きましょう。

2020-09-27 12:18 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        self.showAlert(title: "ログインエラー", message: "error: \(errorMessage)", actions: [closeAction])
```suggestion
       showAlert(title: "ログインエラー", message: "error: \(errorMessage)", actions: [closeAction])
```
selfは不要です。

2020-09-27 12:55 UTC, Karibash requested changes

2020-09-27 12:55 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        else {
また、今回の場合であればguard節を利用する方が適しているかと思います。
```swift
        guard let accessToken = AccessToken.current else {
            Logger.error("Facebookログイン失敗 ユーザーID不明")
            didLoginFailed(errorMessage: "Facebookログイン失敗 ユーザーID不明")
        }
        Logger.debug("Facebookログイン完了 ユーザーID [\(accessToken.userID)]")
        didLoginSuccessAction(userID: accessToken.userID)
```

2020-09-27 13:15 UTC, Karibash requested changes

2020-09-27 13:15 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private let SELECT_FEEDS_SEGUE_ID = "selectFeeds"
```suggestion
```
使用していない不要な変数は削除しましょう。

2020-09-28 02:22 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private func didLoginSuccessAction(userID: String) {
お忙しい中、ご確認頂きましてありがとうございます！
修正致しました。

2020-09-28 02:23 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        else {
guard節に変更致しました。

2020-09-28 02:23 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +        self.showAlert(title: "ログインエラー", message: "error: \(errorMessage)", actions: [closeAction])
手癖で書いてしまいますね・・・
気をつけます。

2020-09-28 02:24 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +    private let SELECT_FEEDS_SEGUE_ID = "selectFeeds"
削除致しました。

2020-09-29 12:01 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            showAlert(title: "ログインエラー", message: "error: \(error!.localizedDescription)", actions: [closeAction])
本来であればLoginFailedErrorのような独自定義のエラーを実装するのが好ましいですが、今回は研修なので一旦はStringを渡すようにしておきましょうか。
研修後に時間が余ったら改修しましょう。

2020-09-29 13:49 UTC, Karibash requested changes

2020-09-29 13:49 UTC, Karibash commented on RSSReader-Maruyama/Modules/ItemList/ItemListViewController.swift
> +        logoutFromGoogle()
今ユーザーが何のサービスでログインしているのかに応じてログアウト処理も切り替えるべきでは無いでしょうか？

2020-09-29 13:49 UTC, Karibash commented on RSSReader-Maruyama/Modules/ItemList/ItemListViewController.swift
> +        userRepository.delete()
ログアウト成功後にユーザーデータを削除するようにしましょう。

2020-09-29 13:49 UTC, Karibash commented on RSSReader-Maruyama/Modules/ItemList/ItemListViewController.swift
> +        NotificationCenter.default.post(name: .didLogOut, object: nil)
画面遷移処理をItemListTabBarControllerに行わせる理由は何でしょうか？
ItemListViewControllerで行うのではダメなのでしょうか？

2020-09-30 16:24 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/ItemList/ItemListViewController.swift
> +        logoutFromGoogle()
LoginControllerクラス（クラス名はどのようなものが適切でしょうか？）を作成して管理する方法でよろしいでしょうか？

2020-09-30 16:24 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/ItemList/ItemListViewController.swift
> +        userRepository.delete()
修正しました。

2020-09-30 16:24 UTC, Uyoshima commented on RSSReader-Maruyama/Modules/ItemList/ItemListViewController.swift
> +        NotificationCenter.default.post(name: .didLogOut, object: nil)
ItemListViewから遷移するよりも、ログイン時に利用するViewControllerを管理しているTabBarControllerの方が自然かな？と思いそうしました。
また、TabControllerのに実装予定の「設定」画面にログアウトボタンを配置しようと考えています。
ログアウトボタンが配置されているViewControllerから遷移させるほうが良いでしょうか？

2020-10-08 15:33 UTC, Karibash requested changes

2020-10-08 15:33 UTC, Karibash commented on RSSReader-Maruyama/Extensions/NotificationName+Extension.swift
> +    static let didLogOut = Notification.Name("didLogOut")
使わなくなった物は消しましょう

2020-10-08 15:42 UTC, Karibash requested changes

2020-10-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/AppleAuthenticationStrategy.swift
> +    var handler: ((Result<User, Error>) -> Void)?
```suggestion
```
使用していない変数は削除しましょう

2020-10-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/AppleAuthenticationStrategy.swift
> +    }
実装を忘れているのか、あえて実装していないのかが分からないです。
あえて実装していないのであればコメントを残すようにしましょう。
```suggestion
    /// ToDo: 実装していない理由
    func logout(_ user: User) {
    }
```

2020-10-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/GoogleAuthenticationStrategy.swift
> +        self.delegate = delegate
```suggestion
       delegate = delegate
```
self不要

2020-10-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/FacebookAuthenticationStrategy.swift
> +        self.delegate.didLogin(.failure(error))
```suggestion
       delegate.didLogin(.failure(error))
```
self不要

2020-10-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/FacebookAuthenticationStrategy.swift
> +        self.delegate.didLogin(.success(User(id: accessToken.userID, type: .facebook)))
```suggestion
       delegate.didLogin(.success(User(id: accessToken.userID, type: .facebook)))
```
self不要

2020-10-08 15:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/AppleAuthenticationStrategy.swift
> +        return self.presentingViewController.view.window!
```suggestion
        return presentingViewController.view.window!
```
self不要

2020-10-08 15:47 UTC, Karibash requested changes

2020-10-08 15:47 UTC, Karibash commented on RSSReader-Maruyama/Serviceis/AuthenticationService.swift
> +enum SocialServiceAuthError: Error {
```suggestion
enum AuthenticationServiceAuthError: Error {
```
AuthenticationServiceのサービスなのにSocialServiceAuthErrorは変な気がします。

2020-10-08 15:47 UTC, Karibash commented on RSSReader-Maruyama/Repositories/UserSettingRepository.swift
> +//
使用していないクラスは削除しましょう。

2020-10-08 15:47 UTC, Karibash commented on RSSReader-Maruyama/Repositories/ItemRepository.swift
> +//
使用していないクラスは削除しましょう。

2020-10-08 15:47 UTC, Karibash commented on RSSReader-Maruyama/Repositories/FeedRepository.swift
> +//
使用していないクラスは削除しましょう。

2020-10-09 02:22 UTC, Uyoshima commented on RSSReader-Maruyama/Extensions/NotificationName+Extension.swift
> +    static let didLogOut = Notification.Name("didLogOut")
削除しました。

2020-10-09 02:22 UTC, Uyoshima commented on RSSReader-Maruyama/Strategies/AppleAuthenticationStrategy.swift
> +    var handler: ((Result<User, Error>) -> Void)?
削除しました。

2020-10-09 02:23 UTC, Uyoshima commented on RSSReader-Maruyama/Strategies/AppleAuthenticationStrategy.swift
> +    }
実装しました。

2020-10-09 02:25 UTC, Uyoshima commented on RSSReader-Maruyama/Repositories/FeedRepository.swift
> +//
削除しました。

2020-10-09 02:25 UTC, Uyoshima commented on RSSReader-Maruyama/Repositories/ItemRepository.swift
> +//
削除しました。

2020-10-09 02:25 UTC, Uyoshima commented on RSSReader-Maruyama/Repositories/UserSettingRepository.swift
> +//
削除しました。

2020-10-09 02:25 UTC, Uyoshima commented on RSSReader-Maruyama/Serviceis/AuthenticationService.swift
> +enum SocialServiceAuthError: Error {
修正しました。

2020-10-09 02:26 UTC, Uyoshima commented on RSSReader-Maruyama/Strategies/AppleAuthenticationStrategy.swift
> +        return self.presentingViewController.view.window!
削除しました。

2020-10-09 02:26 UTC, Uyoshima commented on RSSReader-Maruyama/Strategies/FacebookAuthenticationStrategy.swift
> +        self.delegate.didLogin(.success(User(id: accessToken.userID, type: .facebook)))
削除しました。

2020-10-09 02:26 UTC, Uyoshima commented on RSSReader-Maruyama/Strategies/FacebookAuthenticationStrategy.swift
> +        self.delegate.didLogin(.failure(error))
削除しました。

2020-10-09 02:28 UTC, Uyoshima commented on RSSReader-Maruyama/Strategies/GoogleAuthenticationStrategy.swift
> +        self.delegate = delegate
selfを削除すると、以下のエラーが表示されてしまいます。
Cannot assign to value: 'delegate' is a 'let’ constant
Add explicit 'self.' to refer to mutable property of 'AppleAuthenticationStrategy'

メンバ変数のdelegateを違う名称にした方がよろしいでしょうか？

2020-10-09 12:37 UTC, Karibash requested changes

2020-10-09 12:37 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            self.didLoginFailed(errorMessage: error.localizedDescription)
```suggestion
           didLoginFailed(errorMessage: error.localizedDescription)
```
self不要

2020-10-09 12:37 UTC, Karibash commented on RSSReader-Maruyama/Modules/Login/LoginViewController.swift
> +            self.didLoginSuccess(user: user)
```suggestion
           didLoginSuccess(user: user)
```
self不要

2020-10-09 12:42 UTC, Karibash commented on RSSReader-Maruyama/Strategies/GoogleAuthenticationStrategy.swift
> +        self.delegate = delegate
すみません。僕の指摘ミスでした。

2020-10-09 12:47 UTC, Karibash commented
@Uyoshima Appleサインインの時だけKeyChainを使用してるのは何故でしょうか？

2020-10-11 05:24 UTC, Uyoshima commented
> @Uyoshima Appleサインインの時だけKeyChainを使用してるのは何故でしょうか？

AppleSignInの実装のサンプルを参考にしました。
頂いてる要件には「UserDefaultに保存する」とありましたので、Keychainは利用せずUserDefaultに統一しました。

2020-10-12 01:45 UTC, fujino-sp approved these changes

2020-10-12 13:49 UTC, Karibash approved these changes

2020-10-13 01:33 UTC, merged